# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='from_email',
        ),
        migrations.AlterField(
            model_name='message',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='author_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
