# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mailing.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mailing', '0002_message_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.PositiveIntegerField(blank=True, null=True)),
                ('token', models.CharField(default=mailing.models.generate_message_token, max_length=64, unique=True)),
                ('author_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='new_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.MessageAuthor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='from_email',
            field=models.EmailField(blank=True, null=True),
        ),
    ]
