# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20171130_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='new_author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.MessageAuthor'),
        ),
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
