language: python
python:
    - 3.5
    - 3.6
install:
    - pip install -r requirements.txt python-coveralls flake8
script:
    - coverage run manage.py test
    - ./manage.py migrate
after_success:
    - coveralls
    - flake8 .
