# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
