# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversationabouttalk_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AlterField(
            model_name='conversationabouttalk',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_conversationabouttalk_subscribers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationwithparticipant',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_conversationwithparticipant_subscribers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
