# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:31
from __future__ import unicode_literals

import conversations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversationabouttalk_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(default=conversations.utils.generate_message_token, max_length=64, unique=True),
        ),
    ]
