# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
