# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_conference_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='home',
            field=models.TextField(blank=True, default='', verbose_name='Homepage (markdown)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Conference name'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Staff members'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue',
            field=models.TextField(blank=True, default='', verbose_name='Venue information'),
        ),
    ]
