# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_auto_20170605_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
