# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_auto_20170801_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='reply_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reply email'),
        ),
    ]
