# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0005_auto_20170605_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='participant',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='participant',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='participant',
            name='mastodon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mastodon'),
        ),
        migrations.AddField(
            model_name='participant',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='participant',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='biography',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cfp.TalkCategory', verbose_name='Talk Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(verbose_name='Description of your talk'),
        ),
    ]
