# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0005_conference_reply_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
