# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_auto_20170811_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='secure_domain',
            field=models.BooleanField(default=True, verbose_name='Secure domain'),
        ),
    ]
