# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0006_auto_20170606_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='external_css_link',
            field=models.URLField(blank=True),
        ),
    ]
