# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('cfp', '0007_conference_secure_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('capacity', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Beginning date and time'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='secure_domain',
            field=models.BooleanField(default=True, verbose_name='Secure domain (HTTPS)'),
        ),
        migrations.AddField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfp.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('site', 'name')]),
        ),
    ]
