# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_auto_20170606_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
