# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0011_auto_20171005_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='confirmed',
            field=models.NullBooleanField(default=None),
        ),
    ]
