# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0014_auto_20171016_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='schedule_redirection_url',
            field=models.URLField(blank=True, default='', verbose_name='Schedule redirection URL'),
        ),
    ]
