# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0015_conference_schedule_redirection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='sms_prefered',
            field=models.BooleanField(default=False, verbose_name='SMS prefered'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='schedule_redirection_url',
            field=models.URLField(blank=True, default='', help_text='If specified, schedule tab will redirect to this URL.', verbose_name='Schedule redirection URL'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
