# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0016_auto_20171103_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='Invited speaker'),
        ),
    ]
