# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0017_auto_20171103_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='acceptances_disclosure_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Acceptances disclosure date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
