# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0018_auto_20171104_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Show the tag on the program'),
        ),
    ]
