# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0019_tag_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Show the tag on the staff program'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Show the tag on the public program'),
        ),
    ]
