# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:59
from __future__ import unicode_literals

import cfp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0020_auto_20171116_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='video_publishing_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Video publishing date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='label',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(help_text='This description will be visible on the program.', verbose_name='Description of your talk'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='materials',
            field=models.FileField(blank=True, help_text='You can use this field to share some materials related to your intervention.', null=True, upload_to=cfp.models.talks_materials_destination, verbose_name='Materials'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='notes',
            field=models.TextField(blank=True, help_text='If you have any constraint or if you have anything that may help you to select your talk, like a video or slides of your talk, please write it down here. This field will only be visible by organizers.', verbose_name='Message to organizers'),
        ),
    ]
