# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0021_conference_video_publishing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='volunteers',
            new_name='old_volunteers',
        ),
        migrations.AlterField(
            model_name='activity',
            name='old_volunteers',
            field=models.ManyToManyField(blank=True, related_name='old_activities', to='cfp.Volunteer', verbose_name='Volunteer'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='cfp.Activity', verbose_name='Activities'),
        ),
    ]
