# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0023_auto_20171201_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='old_volunteers',
        ),
    ]
