# Generated by Django 2.0 on 2017-12-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0024_remove_activity_old_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mailing.MessageThread'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfp.TalkCategory', verbose_name='Talk Category'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mailing.MessageThread'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfp.Room'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfp.Track', verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mailing.MessageThread'),
        ),
    ]
