# Generated by Django 2.0 on 2019-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0025_auto_20171216_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='End of the conference date'),
        ),
    ]
