# Generated by Django 3.1 on 2020-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0026_conference_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_licence',
            field=models.CharField(choices=[('CC-Zero CC-BY', 'CC-Zero CC-BY'), ('CC-BY-SA', 'CC-BY-SA'), ('CC-BY-ND', 'CC-BY-ND'), ('CC-BY-NC', 'CC-BY-NC'), ('CC-BY-NC-SA', 'CC-BY-NC-SA'), ('CC-BY-NC-ND', 'CC-BY-NC-ND')], default='CC-BY-SA', max_length=32, verbose_name='Video licence'),
        ),
    ]
