# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
    ]
