# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participation',
            managers=[
            ],
        ),
    ]
