# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170429_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Github'),
        ),
    ]
