# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 14:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160611_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponyconfspeaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
