# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160709_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='video_licence',
            field=models.IntegerField(choices=[(1, 'CC-Zero'), (2, 'CC-BY'), (3, 'CC-BY-SA'), (4, 'CC-BY-ND'), (5, 'CC-BY-NC'), (6, 'CC-BY-NC-SA'), (7, 'CC-BY-NC-ND')], default=1),
        ),
        migrations.AddField(
            model_name='participation',
            name='videotaped',
            field=models.BooleanField(default=True, verbose_name="I'm ok to be recorded on video"),
        ),
    ]
