# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160615_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='review_topics',
        ),
    ]
