# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_participation_review_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='sound',
            field=models.BooleanField(default=False, verbose_name='I need sound'),
        ),
    ]
