# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160710_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
        migrations.AddField(
            model_name='participation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
