# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160712_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='video_licence',
            field=models.IntegerField(choices=[(1, 'CC-Zero'), (2, 'CC-BY'), (3, 'CC-BY-SA'), (4, 'CC-BY-ND'), (5, 'CC-BY-NC'), (6, 'CC-BY-NC-SA'), (7, 'CC-BY-NC-ND')], default=1, verbose_name='Video licence'),
        ),
    ]
