# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160625_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='orga',
            field=models.BooleanField(default=False),
        ),
    ]
