# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160723_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='constraints',
            field=models.TextField(blank=True, verbose_name='Constraints'),
        ),
    ]
