# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_participation_orga'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
