# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160808_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='homestay',
            field=models.BooleanField(default=False, verbose_name='Ok for homestay?'),
        ),
        migrations.AddField(
            model_name='participation',
            name='need_hosting',
            field=models.BooleanField(default=False, verbose_name='Need hosting?'),
        ),
        migrations.AddField(
            model_name='participation',
            name='need_transport',
            field=models.BooleanField(default=False, verbose_name='Need transport?'),
        ),
    ]
