# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160808_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='video_licence',
            field=models.IntegerField(choices=[(1, 'CC-Zero'), (2, 'CC-BY'), (3, 'CC-BY-SA'), (4, 'CC-BY-ND'), (5, 'CC-BY-NC'), (6, 'CC-BY-NC-SA'), (7, 'CC-BY-NC-ND')], default=2, verbose_name='Video licence'),
        ),
    ]
