# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_availabilitytimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='transport_city_outward',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Departure city'),
        ),
        migrations.AddField(
            model_name='participation',
            name='transport_city_return',
            field=models.CharField(blank=True, default='', help_text='If different from departure city', max_length=256, verbose_name='Return city'),
        ),
    ]
