# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20161013_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='need_transport',
            field=models.NullBooleanField(default=None, verbose_name='Defray transportation?'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='transport',
            field=models.ManyToManyField(blank=True, to='accounts.Transport', verbose_name='I want to travel by'),
        ),
    ]
