# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sound',
            field=models.BooleanField(default=False),
        ),
    ]
