# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='talk',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='topic',
            managers=[
            ],
        ),
    ]
