# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_participation_review_topics'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='reviewers',
            field=models.ManyToManyField(blank=True, to='accounts.Participation'),
        ),
    ]
