# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='video',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='URL vidéo'),
        ),
    ]
