# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:52
from __future__ import unicode_literals

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='dudule', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
