# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_topic_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.IntegerField(choices=[(1, 'conference short'), (2, 'conference long'), (3, 'workshop'), (4, 'stand'), (5, 'other')], default=1),
        ),
    ]
