# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:02
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_topic_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='talk',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='topic',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
