# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
