# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20160611_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speach',
            old_name='user',
            new_name='speaker',
        ),
        migrations.AlterUniqueTogether(
            name='speach',
            unique_together=set([('speaker', 'talk'), ('order', 'talk')]),
        ),
    ]
