# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='abstract',
            field=models.CharField(blank=True, max_length=255, verbose_name='Abstract'),
        ),
        migrations.AddField(
            model_name='talk',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
