# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_auto_20160921_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Track', verbose_name='Destination track'),
        ),
    ]
