# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_topic_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cfp_closing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='cfp_opening_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
