# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_topic_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='cfp',
            field=models.IntegerField(choices=[(0, 'Forthcoming (closed)'), (1, 'Open'), (2, 'Completed (closed)')], default=0),
        ),
    ]
