# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0013_auto_20160928_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Managers'),
        ),
    ]
