# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_track_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
