# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_auto_20161005_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
