# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_auto_20161011_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(help_text='After submission, title can only be changed by the staff.', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='The topics can not be changed after submission.', to='proposals.Topic', verbose_name='Topics'),
        ),
    ]
