# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 21:21
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_auto_20161015_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorful.fields.RGBColorField(default='#ffffff', verbose_name='Color on program'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Default duration (min)'),
        ),
    ]
