# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_auto_20161016_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='plenary',
            field=models.BooleanField(default=False),
        ),
    ]
