# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_auto_20161106_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='subscriptions_open',
            field=models.BooleanField(default=False),
        ),
    ]
