# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_opening_closing_dates(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Conference = apps.get_model('proposals', 'Conference')
    Event = apps.get_model('proposals', 'Event')
    for conf in Conference.objects.all():
        for event in Event.objects.filter(site=conf.site).all():
            event.opening_date = conf.cfp_opening_date
            event.closing_date = conf.cfp_closing_date
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_conference_subscriptions_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closing_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='opening_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_opening_closing_dates),
        migrations.RemoveField(
            model_name='conference',
            name='cfp_closing_date',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='cfp_opening_date',
        ),
    ]
