# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_auto_20161113_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='materials',
            field=models.FileField(help_text='You can use this field to share some materials related to your intervention.', null=True, upload_to='', verbose_name='Materials'),
        ),
    ]
