# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0029_talk_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='materials',
            field=models.FileField(help_text='You can use this field to share some materials related to your intervention.', null=True, upload_to=proposals.models.talk_materials_destination, verbose_name='Materials'),
        ),
    ]
